# Generated by Django 6.0.5 on 2026-06-02 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ruta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Paquete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destinatario", models.CharField(max_length=120)),
                ("peso_kg", models.PositiveIntegerField()),
                ("tipo", models.CharField(max_length=20)),
                ("estado", models.CharField(blank=True, default="", max_length=60)),
                (
                    "codigo_rastreo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paquetes",
                        to="catalog.ruta",
                    ),
                ),
            ],
        ),
    ]
